# Generated by Django 5.2.3 on 2025-07-09 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('BGN', 'Bulgarian Lev'), ('GBP', 'British Pound')], default='BGN', help_text="User's preferred currency", max_length=3)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture (max 5MB)', null=True, upload_to='profile_pics/')),
                ('email_notifications', models.BooleanField(default=True)),
                ('budget_alerts', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
