# Generated by Django 5.2.3 on 2025-07-05 07:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Goal name (e.g., Summer Vacation, New Laptop, Wedding Fund)', max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target amount to save', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current amount saved', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('target_date', models.DateField(blank=True, help_text='Target date to reach goal (optional)', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this goal', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this goal is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
