# Generated by Django 5.2.3 on 2025-07-05 07:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import expenses.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(help_text='Brief description of the expense', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or details (optional)', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date when the expense occurred')),
                ('receipt_image', models.ImageField(blank=True, help_text='Upload receipt image (optional)', null=True, upload_to=expenses.models.expense_receipt_path)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet (PayPal, etc.)'), ('other', 'Other')], default='cash', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Where the expense occurred (optional)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
