# Generated by Django 5.2.3 on 2025-07-24 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly_summary', 'Monthly Financial Summary'), ('category_breakdown', 'Category Analysis Report'), ('budget_performance', 'Budget vs Actual Report'), ('subscription_analysis', 'Subscription Cost Analysis'), ('yearly_overview', 'Annual Financial Overview')], max_length=120)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_subscriptions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_utilization', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('categories_analyzed', models.IntegerField(default=0)),
                ('transactions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
