# Generated by Django 5.2.3 on 2025-07-05 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Groceries & Food, Transportation & Fuel, Entertainment & Dining)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this category includes', max_length=500, null=True)),
                ('color', models.CharField(default='#6B8E23', help_text='Color for charts and visual representation', max_length=7)),
                ('icon', models.CharField(default='fas fa-shopping-cart', help_text='Choose an icon to represent this category', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently in use')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
