# Generated by Django 5.2.3 on 2025-07-07 08:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subscription name (e.g., Netflix, Spotify, Gym Membership)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged per billing cycle', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='How often you are charged', max_length=20)),
                ('start_date', models.DateField(help_text='When this subscription started')),
                ('next_payment_date', models.DateField(help_text='Next scheduled payment date')),
                ('end_date', models.DateField(blank=True, help_text='When subscription ends (leave empty for ongoing)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is currently active')),
                ('auto_add_expense', models.BooleanField(default=False, help_text='Automatically create expense entries when payments are due')),
                ('description', models.TextField(blank=True, help_text='Optional notes about this subscription', null=True)),
                ('website_url', models.URLField(blank=True, help_text='Subscription service website (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category for this subscription', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['next_payment_date', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
